schema_version: 1

context:
  name: xgboost_ray
  version: "0.1.19"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 03e3661712daa1c2208086161881129bb6ec3e19bcd04742ace11191922236d0

build:
  number: 1
  noarch: python
  script:
    - rm -rf examples
    - ${{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.16
    - packaging
    - pandas
    - ray-train >=2.7
    - wrapt >=1.12.1
    - xgboost >=0.90

tests:
  - python:
      imports:
        - xgboost_ray
      pip_check: false
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: A Ray backend for distributed XGBoost
  homepage: https://github.com/ray-project/xgboost_ray
  repository: https://github.com/ray-project/xgboost_ray

extra:
  recipe-maintainers:
    - timkpaine
